// Chat messages.
//
// A message is deliberately dumb: a role, a string, and an optional timestamp.
// There is no per-message token count, no attachment, no streaming flag, because
// the chat engine renders the whole history into a single prompt string on every
// turn. Keeping the two representations apart means the UI can hold a rich
// conversation while the model still sees a flat transcript, which is the only
// shape a byte-level language model can consume.

/// Who produced a message.
enum ChatRole {
  /// Instructions and context the user did not type.
  system,

  /// Text typed or spoken by the user.
  user,

  /// Text generated by the model.
  assistant,

  /// The output of a tool the assistant invoked.
  tool,
}

/// One turn of a conversation.
class ChatMessage {
  /// Creates a message.
  const ChatMessage({
    required this.role,
    required this.content,
    this.name,
    this.at,
  });

  /// Who said it.
  final ChatRole role;

  /// What was said.
  final String content;

  /// Tool name, for [ChatRole.tool] messages only.
  final String? name;

  /// When it was said, in UTC.
  final DateTime? at;

  /// A copy with selected fields replaced.
  ChatMessage copyWith({
    ChatRole? role,
    String? content,
    String? name,
    DateTime? at,
  }) {
    return ChatMessage(
      role: role ?? this.role,
      content: content ?? this.content,
      name: name ?? this.name,
      at: at ?? this.at,
    );
  }

  /// A user message.
  static ChatMessage user(String content) =>
      ChatMessage(role: ChatRole.user, content: content, at: DateTime.now().toUtc());

  /// An assistant message.
  static ChatMessage assistant(String content) => ChatMessage(
        role: ChatRole.assistant,
        content: content,
        at: DateTime.now().toUtc(),
      );

  /// A tool-result message.
  static ChatMessage tool(String name, String content) => ChatMessage(
        role: ChatRole.tool,
        content: content,
        name: name,
        at: DateTime.now().toUtc(),
      );

  /// A system message.
  static ChatMessage system(String content) =>
      ChatMessage(role: ChatRole.system, content: content);

  /// JSON form, written to the persisted transcript.
  Map<String, Object?> toJson() => <String, Object?>{
        'role': role.name,
        'content': content,
        if (name != null) 'name': name,
        if (at != null) 'at': at!.toUtc().toIso8601String(),
      };

  /// Parses [toJson].
  ///
  /// Throws [FormatException] rather than guessing: a transcript with an
  /// unknown role cannot be rendered meaningfully, and silently treating it as
  /// `user` would misattribute text to the person using the app.
  static ChatMessage fromJson(Map<String, Object?> json) {
    final Object? role = json['role'];
    final Object? content = json['content'];
    if (role is! String || content is! String) {
      throw const FormatException(
        'a chat message needs a string "role" and a string "content"',
      );
    }
    ChatRole parsed;
    switch (role) {
      case 'system':
        parsed = ChatRole.system;
      case 'user':
        parsed = ChatRole.user;
      case 'assistant':
        parsed = ChatRole.assistant;
      case 'tool':
        parsed = ChatRole.tool;
      default:
        throw FormatException('unknown chat role "$role"');
    }
    final Object? at = json['at'];
    return ChatMessage(
      role: parsed,
      content: content,
      name: json['name'] is String ? json['name']! as String : null,
      at: at is String ? DateTime.tryParse(at) : null,
    );
  }

  @override
  String toString() => '${role.name}: $content';
}

/// The instruction that turns a text-completion model into an assistant.
///
/// Kept short on purpose. Every token here is a token the model cannot spend on
/// the user's actual conversation, and a small model follows a five-line brief
/// far more reliably than a page of rules.
const String kDefaultSystemPrompt = '''
You are Harbor, an assistant that runs entirely on the user's own device.
Answer in complete, natural sentences. Structure responses clearly: short intro, then facts, then a concrete next step when useful.
If you need a fact you cannot know, say so — never guess.
You may call one tool per reply, exactly like this: <tool name="device.battery">{}</tool>
Only use tools from the list you are given, and never invent a tool's result.
After a tool result is provided, use it in your answer and explain what it means.''';